version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db-innovatech
    restart: always
    environment:
      # Verifica que estos coincidan con tu application.properties del Back
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: bd_innovatech 
    ports:
      - "3306:3306"
    volumes:
      - data_innovatech:/var/lib/mysql

  backend-ventas:
    image: [TU_ID_AWS].dkr.ecr.us-east-1.amazonaws.com/back-ventas:latest
    container_name: back-ventas
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    image: [TU_ID_AWS].dkr.ecr.us-east-1.amazonaws.com/front-tienda:latest
    container_name: front-tienda
    ports:
      - "80:80"
    depends_on:
      - backend-ventas

volumes:
  data_innovatech: # Nombre de volumen profesional
